services:
    postgres:
        image: bitnami/postgresql:latest
        container_name: odonto-api
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: meudente
        volumes:
           - ./docker:/docker-entrypoint-initdb.d
